language: node_js

node_js:
  - stable

cache:
  directories:
  - node_modules

install:
  - npm install

script:
  - npm test

before_script:
  - npm install codeclimate-test-reporter istanbul -g

after_success:
  - COVERALLS_REPO_TOKEN=$coveralls_repo_token 
  - npm run coverage
  - codeclimate-test-reporter < ./coverage/lcov.info